package test;

import java.awt.Dialog;
import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import com.mycompany.star.rating.EventStarRating;
import com.netnet.moviedex.Movie;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

/**
 *
 * @author Aaron Penetrante
 */
public class DetailPopup extends javax.swing.JPanel implements EventStarRating {

    /**
     * Creates new form DetailPopup
     */
    boolean closePanel = false;
    Movie movie;
    private BufferedImage image;

    public void closePanel(boolean b) {
        boolean old = this.closePanel;
        this.closePanel = b;
        firePropertyChange("closePanel", old, this.closePanel);

    }

    public DetailPopup(Movie m) {
        this.movie = m;
        initComponents();
        try {
            image = ImageIO.read(getClass().getResource(m.getCoverLink()));
        } catch (Exception e) {
            e.printStackTrace();
        }
        jLabel2.setText(m.getTitle());
        jLabel4.setText(Double.toString(m.getScore()));

    }

    @Override
    public void selected(int star) {
        
        double old = movie.getScore();
        System.out.println("Star received in DetailPopup: " + star);
        SwingUtilities.invokeLater(() -> {
            jLabel4.setText(star + "/5");
            firePropertyChange("rating", old, star);
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane(){
            @Override
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                if (image != null) {
                    g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), this);
                }
            }
        };
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ratebtn1 = new ratebtn.Ratebtn();
        star1 = new com.mycompany.star.rating.Star();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 38, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setBackground(new java.awt.Color(200, 200, 200));
        jLayeredPane2.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 250));

        jLayeredPane1.setBackground(new java.awt.Color(147, 0, 58));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[description]");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 161, 501, 160));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Movie Title");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 0, -1, 51));

        ratebtn1.setBackground(new java.awt.Color(255, 255, 255));
        ratebtn1.setText("RATE");
        ratebtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ratebtn1.setRadius(10);
        ratebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratebtn1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ratebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 93, 86, 40));

        star1.setSelected(true);
        star1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 57, 21, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rating");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 57, 47, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0/5");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 57, 46, 24));

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 228, 620, 330));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 38, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void star1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_star1ActionPerformed

    private void ratebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratebtn1ActionPerformed
        // TODO add your handling code here:
        openRatePopup();
    }//GEN-LAST:event_ratebtn1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isLeftMouseButton(evt)) {
            closePanel(true);
            
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void openRatePopup() {
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        JDialog rateDialog = new JDialog(parentWindow, "Rate Movie", Dialog.ModalityType.APPLICATION_MODAL);
        rateDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        rateDialog.setSize(524, 329);
        rateDialog.setLocationRelativeTo(this);

        rateDialog.setContentPane(new RatePopup(this));
        rateDialog.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    public ratebtn.Ratebtn ratebtn1;
    private com.mycompany.star.rating.Star star1;
    // End of variables declaration//GEN-END:variables

}
