package test;

import com.mycompany.star.rating.EventStarRating;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author Aaron Penetrante
 */
public class RatePopup extends javax.swing.JPanel {

    /**
     * Creates new form RatePopup
     */
    private EventStarRating event;
    
    public RatePopup(EventStarRating event) {
        initComponents();
        setBackground(Color.decode("#93003A")); 
        
       this.event = event;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        starRating1 = new com.mycompany.star.rating.StarRating();
        jLabel1 = new javax.swing.JLabel();
        submitbtn1 = new submitbtn.Submitbtn();

        setBackground(new java.awt.Color(147, 0, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Let us know.");

        submitbtn1.setBackground(new java.awt.Color(255, 255, 255));
        submitbtn1.setText("SUBMIT");
        submitbtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitbtn1.setRadius(10);
        submitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(starRating1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(submitbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(starRating1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtn1ActionPerformed
        // TODO add your handling code here:
        int star = starRating1.getStar();
        System.out.println("submitted: " + star);
        
        if (event != null){
         event.selected(star);
        }
        
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_submitbtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.mycompany.star.rating.StarRating starRating1;
    private submitbtn.Submitbtn submitbtn1;
    // End of variables declaration//GEN-END:variables
}
