/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.netnet.moviedex.components;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.netnet.moviedex.Movie;
import com.netnet.moviedex.Movie.MovieStatus;
import com.netnet.moviedex.User;
import com.netnet.moviedex.UserData;
import java.util.HashMap;



/**
 *
 * @author quasar
 */
public class previewFrame extends javax.swing.JFrame {

    /**
     * Creates new form previewFrame
     */
    LandingPage landingPage1;
    public previewFrame() {
        initComponents();
        
        Movie[] movies = {
            new Movie("1917", "", 0, MovieStatus.RATED),
            new Movie("1985", "", 0, MovieStatus.UNRATED),
            new Movie("1986", "", 0, MovieStatus.UNRATED),
            new Movie("1987", "", 0, MovieStatus.UNRATED),
            new Movie("1988", "", 0, MovieStatus.UNRATED),
            new Movie("1989", "", 0, MovieStatus.UNRATED),
            new Movie("1990", "", 0, MovieStatus.UNRATED),
            new Movie("1991", "", 0, MovieStatus.UNRATED),
            new Movie("1992", "", 0, MovieStatus.UNRATED),
            new Movie("1993", "", 0, MovieStatus.UNRATED),
            new Movie("1994", "", 0, MovieStatus.UNRATED),
            new Movie("1984", "", 0, MovieStatus.UNRATED),
            new Movie("1985", "", 0, MovieStatus.UNRATED),
            new Movie("1986", "", 0, MovieStatus.UNRATED),
            new Movie("1987", "", 0, MovieStatus.UNRATED),
            new Movie("1988", "", 0, MovieStatus.UNRATED),
            new Movie("1989", "", 0, MovieStatus.UNRATED),
            new Movie("1990", "", 0, MovieStatus.UNRATED),
            new Movie("1991", "", 0, MovieStatus.UNRATED),
            new Movie("1992", "", 0, MovieStatus.UNRATED),
            
                    
        };
        
        User[] users = {
            new User("Guil", "/userIcon.png"),
            new User("Guil2", "/userIcon.png"),
            new User("Guil3", "/userIcon.png"),
            new User("Guil4", "/userIcon.png"),
 
        };
        UserData[] userData = new UserData[users.length];
        HashMap<String, UserData> map = new HashMap<>();
        
        for(int i = 0; i < users.length; i++){
            userData[i] = new UserData(users[i], movies);
            map.put(users[i].getName(), userData[i]);
        }
        
        UserCard[] userCards = new UserCard[users.length];
        
        for(int i = 0; i < userCards.length; i++){
            userCards[i] = new UserCard(userData[i]);
     
        }
        
        Login loginPage = new Login(userCards);
        landingPage1 = new LandingPage(map.get("Guil"));
       
        jPanel1.add(loginPage); 
        
        loginPage.addPropertyChangeListener("username", evt -> {
            String selectedName = (String) evt.getNewValue();
            
            landingPage1 = new LandingPage(map.get(selectedName));
            jPanel1.remove(loginPage); 
            jPanel1.add(landingPage1);
            jPanel1.revalidate();
            jPanel1.repaint();
        });
        
        
             
        
        
        //jPanel1.add(landingPage1);
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1278, 648));

        jPanel1.setBackground(new java.awt.Color(26, 26, 29));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/title.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(previewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(previewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(previewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(previewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatDarculaLaf.setup();
                new previewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
